# Generated by Django 4.2.7 on 2024-02-13 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Geust',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('mobile', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hall', models.CharField(max_length=10)),
                ('movie', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Resrvation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geust', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resrvation', to='Ticket.geust')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resrvation', to='Ticket.movie')),
            ],
        ),
    ]
